export const rewardBlocksAggregatorAbi = [
  {
    inputs: [],
    name: 'HASH',
    outputs: [{ internalType: 'contract IBalance', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'HELI',
    outputs: [{ internalType: 'contract IReward', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'LAMBO',
    outputs: [{ internalType: 'contract IReward', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'NFT_BADGE',
    outputs: [{ internalType: 'contract IBalance', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'NFT_EARLY',
    outputs: [{ internalType: 'contract IBalance', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'NFT_GEM',
    outputs: [{ internalType: 'contract IBalance', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'NFT_GM',
    outputs: [{ internalType: 'contract IBalance', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'NFT_GRAM',
    outputs: [{ internalType: 'contract IBalance', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'NFT_WHALE',
    outputs: [{ internalType: 'contract IBalance', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'SEA',
    outputs: [{ internalType: 'contract ISeaReward', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'WELCOME',
    outputs: [{ internalType: 'contract IReward', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'getPools',
    outputs: [
      { internalType: 'uint256', name: 'heliPool', type: 'uint256' },
      { internalType: 'uint256', name: 'lamboPool', type: 'uint256' },
      { internalType: 'uint256', name: 'welcomePool', type: 'uint256' },
      { internalType: 'uint256', name: 'seaPool', type: 'uint256' },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'address', name: 'user', type: 'address' }],
    name: 'getTotalClaimableReward',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'address', name: 'user', type: 'address' }],
    name: 'getUserStatus',
    outputs: [
      {
        components: [
          {
            components: [
              { internalType: 'bool', name: 'canClaim', type: 'bool' },
              { internalType: 'bool', name: 'alreadyClaimed', type: 'bool' },
              { internalType: 'uint256', name: 'rewardAmount', type: 'uint256' },
              { internalType: 'uint256', name: 'poolBalance', type: 'uint256' },
            ],
            internalType: 'struct RewardBlocksAggregator.BlockStatus',
            name: 'heli',
            type: 'tuple',
          },
          { internalType: 'bool', name: 'heliHasGm', type: 'bool' },
          { internalType: 'bool', name: 'heliHasBadge', type: 'bool' },
          { internalType: 'bool', name: 'heliHasEarly', type: 'bool' },
          {
            components: [
              { internalType: 'bool', name: 'canClaim', type: 'bool' },
              { internalType: 'bool', name: 'alreadyClaimed', type: 'bool' },
              { internalType: 'uint256', name: 'rewardAmount', type: 'uint256' },
              { internalType: 'uint256', name: 'poolBalance', type: 'uint256' },
            ],
            internalType: 'struct RewardBlocksAggregator.BlockStatus',
            name: 'lambo',
            type: 'tuple',
          },
          { internalType: 'bool', name: 'lamboHasGm', type: 'bool' },
          { internalType: 'bool', name: 'lamboHasGem', type: 'bool' },
          { internalType: 'bool', name: 'lamboHasGram', type: 'bool' },
          { internalType: 'bool', name: 'lamboHasWhale', type: 'bool' },
          {
            components: [
              { internalType: 'bool', name: 'canClaim', type: 'bool' },
              { internalType: 'bool', name: 'alreadyClaimed', type: 'bool' },
              { internalType: 'uint256', name: 'rewardAmount', type: 'uint256' },
              { internalType: 'uint256', name: 'poolBalance', type: 'uint256' },
            ],
            internalType: 'struct RewardBlocksAggregator.BlockStatus',
            name: 'welcome',
            type: 'tuple',
          },
          {
            components: [
              { internalType: 'bool', name: 'canClaim', type: 'bool' },
              { internalType: 'bool', name: 'alreadyClaimed', type: 'bool' },
              { internalType: 'uint256', name: 'rewardAmount', type: 'uint256' },
              { internalType: 'uint256', name: 'poolBalance', type: 'uint256' },
            ],
            internalType: 'struct RewardBlocksAggregator.BlockStatus',
            name: 'sea',
            type: 'tuple',
          },
          { internalType: 'bool', name: 'seaIsShark', type: 'bool' },
          { internalType: 'bool', name: 'seaIsVoter', type: 'bool' },
          { internalType: 'bool', name: 'seaIsX', type: 'bool' },
          { internalType: 'uint256', name: 'totalClaimable', type: 'uint256' },
        ],
        internalType: 'struct RewardBlocksAggregator.UserStatus',
        name: '',
        type: 'tuple',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'address', name: 'user', type: 'address' }],
    name: 'hasAnyClaimable',
    outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
    stateMutability: 'view',
    type: 'function',
  },
] as const;
